name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs fetch
          git lfs checkout

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://phuochungus:${HF_TOKEN}@huggingface.co/spaces/phuochungus/Sweat_NSFW_Detection
          git push hf main --force
